Collections:
  - Name: FSAF
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA Titan-XP GPUs
      Architecture:
        - FPN
        - FSAF
        - ResNet
    Paper: https://arxiv.org/abs/1903.00621
    README: configs/fsaf/README.md

Models:
  - Name:
    In Collection: FSAF
    Config:
    Metadata:
      Training Memory (GB): 3.15
      inference time (s/im): 0.08130
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.0 (35.9)
    Weights: http://download.openmmlab.com/mmdetection/v2.0/fsaf/fsaf_pscale0.2_nscale0.5_r50_fpn_1x_coco/fsaf_pscale0.2_nscale0.5_r50_fpn_1x_coco_20200715-b555b0e0.pth

  - Name: fsaf_r50_fpn_1x_coco
    In Collection: FSAF
    Config: configs/fsaf/fsaf_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 3.15
      inference time (s/im): 0.07692
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.4
    Weights: http://download.openmmlab.com/mmdetection/v2.0/fsaf/fsaf_r50_fpn_1x_coco/fsaf_r50_fpn_1x_coco-94ccc51f.pth

  - Name: fsaf_r101_fpn_1x_coco
    In Collection: FSAF
    Config: configs/fsaf/fsaf_r101_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 5.08
      inference time (s/im): 0.09259
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 39.3 (37.9)
    Weights: http://download.openmmlab.com/mmdetection/v2.0/fsaf/fsaf_r101_fpn_1x_coco/fsaf_r101_fpn_1x_coco-9e71098f.pth

  - Name: fsaf_x101_64x4d_fpn_1x_coco
    In Collection: FSAF
    Config: configs/fsaf/fsaf_x101_64x4d_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 9.38
      inference time (s/im): 0.17857
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 42.4 (41.0)
    Weights: http://download.openmmlab.com/mmdetection/v2.0/fsaf/fsaf_x101_64x4d_fpn_1x_coco/fsaf_x101_64x4d_fpn_1x_coco-e3f6e6fd.pth
