Collections:
  - Name: ConsistentTeacher
    Metadata:
      Training Data:
        - COCO
        - VOC0712
      Training Techniques:
        - SGD with momentum
        - Weight decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - FPN
        - FAM3D
    Paper:
      URL: https://arxiv.org/abs/2209.01589
      Title: "Consistent-Teacher: Towards Reducing Inconsistent Pseudo-targets in Semi-supervised Object Detection"
    README: configs/consistent_teacher/README.md
    Code:
      URL:
      Version:

Models:
  - Name:
    In Collection: ConsistentTeacher
    Config: configs/consistent_teacher/consistent-teacher_retinanet_r50_fpn_180k_semi-0.1-coco.py
    Metadata:
      Iterations: 180000
    Results:
      - Task: Semi-Supervised Object Detection
        Dataset: COCO
        Metrics:
          box AP:
    Weights:

  - Name:
    In Collection: ConsistentTeacher
    Config: configs/consistent_teacher/consistent-teacher_retinanet_r50_fpn_180k_semi-0.01-coco.py
    Metadata:
      Iterations: 180000
    Results:
      - Task: Semi-Supervised Object Detection
        Dataset: COCO
        Metrics:
          box AP:
    Weights:

  - Name:
    In Collection: ConsistentTeacher
    Config: configs/consistent_teacher/consistent-teacher_retinanet_r50_fpn_180k_semi-0.02-coco.py
    Metadata:
      Iterations: 180000
    Results:
      - Task: Semi-Supervised Object Detection
        Dataset: COCO
        Metrics:
          box AP:
    Weights:

  - Name:
    In Collection: ConsistentTeacher
    Config: configs/consistent_teacher/consistent-teacher_retinanet_r50_fpn_180k_semi-0.05-coco.py
    Metadata:
      Iterations: 180000
    Results:
      - Task: Semi-Supervised Object Detection
        Dataset: COCO
        Metrics:
          box AP:
    Weights:

  - Name:
    In Collection: ConsistentTeacher
    Config: configs/consistent_teacher/consistent-teacher_retinanet_r50_fpn_720k_semi-coco.py
    Metadata:
      Iterations: 720000
    Results:
      - Task: Semi-Supervised Object Detection
        Dataset: COCO
        Metrics:
          box AP:
    Weights:

  - Name:
    In Collection: ConsistentTeacher
    Config: configs/consistent_teacher/consistent-teacher_retinanet_r50_fpn_72k_semi-voc0712.py
    Metadata:
      Iterations: 72000
    Results:
      - Task: Semi-Supervised Object Detection
        Dataset: VOC0712
        Metrics:
          box AP:
    Weights:
