dist: xenial
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install isort flake8 yapf pytest Cython
  - pip install -r requirements.txt

script:
  - python setup.py check -m -s
  - python setup.py build_ext --inplace
  - py.test -v --doctest-modules
  - flake8 .
  - isort -rc --check-only --diff mmdet/ tools/
  - yapf -r -d --style .style.yapf mmdet/ tools/