Models:
  - Name: retinanet_effb3_fpn_crop896_8x4_1x_coco
    In Collection: RetinaNet
    Config: configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.5
    Weights: url
