Collections:
  - Name: FP16
    Metadata:
      Training Data: COCO
      Training Techniques:
        - Mixed Precision Training
      Training Resources: 8x V100 GPUs
    Paper:
      URL: https://arxiv.org/abs/1710.03740
      Title: "Mixed Precision Training"
    README: configs/fp16/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.0.0/mmdet/core/fp16/hooks.py#L11
      Version: v2.0.0

Models:
