Collections:
  - Name: H-DINO
    Metadata:
      Training Data: COCO
      Training Techniques:
        - AdamW
        - Multi Scale Train
        - Gradient Clip
      Training Resources: 8x 3090 GPUs
      Architecture:
        - ResNet
        - Transformer
    Paper:
      URL: https://arxiv.org/abs/2207.13080
      Title: 'DETRs with Hybrid Matching'
    README: configs/h_dino/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/f4112c9e5611468ffbd57cfba548fd1289264b52/mmdet/models/detectors/dino.py#L17
      Version: v3.0.0

Models:
  - Name: h-dino-4scale_r50_8xb2-12e_coco.py
    In Collection: DINO
    Config: configs/h_dino/h-dino-4scale_r50_8xb2-12e_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 49.1
    Weights: https://download.openmmlab.com/mmdetection/v3.0/
